In [1]:
import numpy as np

## Create numpy array


In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a = [3.14, 4, 1, 2, 3]

In [6]:
np.array(a)

array([3.14, 4.  , 1.  , 2.  , 3.  ])

In [8]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [9]:
a1 = np.array(a)

In [10]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1, 2, 3], 
                [2, 3, 4]])

In [12]:
type(a2)

numpy.ndarray

In [13]:
a2.shape

(2, 3)

In [14]:
a2.ndim

2

In [15]:
a2.dtype

dtype('int32')

In [17]:
a2.size

6

## Create Numpy arrays from Scratch
### zeros, ones, full, arange, linspace

In [20]:
np.zeros([2,4], dtype='int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [23]:
np.ones([3,4], dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.full([3,5], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random

In [28]:
np.random.random((4,4))

array([[0.74729233, 0.04279893, 0.91045133, 0.80764117],
       [0.0958605 , 0.00520827, 0.94204346, 0.00689925],
       [0.54379   , 0.54662763, 0.20771506, 0.2718577 ],
       [0.03284348, 0.7169805 , 0.14268895, 0.93669729]])

In [29]:
np.random.random((4,4))

array([[0.18726104, 0.33596101, 0.03394123, 0.54468257],
       [0.7547995 , 0.53696112, 0.64458275, 0.73529417],
       [0.535262  , 0.66356626, 0.69845214, 0.44793172],
       [0.91265001, 0.75224608, 0.60124682, 0.2631315 ]])

In [32]:
# seed for reproducibility

np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [33]:
np.random.normal(0, 1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [35]:
np.random.randint(0, 10, (4,5))

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [36]:
np.random.rand(3,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957]])

## Array indexing and Slicing

### One-dimensional subarray

In [40]:
x1 = np.random.randint(0, 20, size=6)


In [41]:
x1

array([ 5,  0, 17, 18,  4,  2])

In [42]:
x1[4]

4

In [44]:
x1[:]

array([ 5,  0, 17, 18,  4,  2])

### Multi-dimensional array

In [45]:
x2 = np.random.randint(0, 20, (4,5))

In [46]:
x2

array([[16,  3,  2, 10, 13],
       [16,  7,  9,  0, 10],
       [18, 11,  2,  2,  3],
       [ 3, 18, 14,  3, 17]])

In [60]:
x2[2, ::-1]

array([ 3,  2,  2, 11, 18])

### Reshaping of Array and Transpose

In [62]:
x3 = np.arange(1, 10)

In [63]:
x3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x3.shape

(9,)

In [71]:
x3 = x3.reshape((3, 3))

In [72]:
x3.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Array Concatenation and Splitting


In [74]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [81]:
np.concatenate((x, y))  

array([1, 2, 3, 3, 2, 1])

In [83]:
grip = np.array([[1, 2, 3],
                [4, 5, 6]])

In [87]:
np.concatenate((grip, grip), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [103]:
#vstack

x = np.arange(1, 4)
print(x)
y = np.random.randint(1, 4, (2,3))
print(y)

[1 2 3]
[[1 3 3]
 [1 1 1]]


In [99]:
np.vstack((x,y))

array([[1, 2, 3],
       [3, 3, 2],
       [1, 1, 1]])

In [104]:
#hstack
grip = np.array([[99],
                [99]])

np.hstack((y, grip))

array([[ 1,  3,  3, 99],
       [ 1,  1,  1, 99]])

### spliting of arrays

In [113]:
x = np.random.randint(1, 10, (1, 10)).reshape(10)
x

array([2, 3, 3, 9, 2, 6, 9, 5, 1, 3])

In [114]:
np.split(x, [3, 5])

[array([2, 3, 3]), array([9, 2]), array([6, 9, 5, 1, 3])]